### ISSUE TITLE
Sample Connversion escape fails

### ISSUE THREAD

**Issue by theSundayProgrammer** [arcapos/luatemplate#1]
Here is the output after running  ttest on escape.lt
$ lua ttest.lua  escape.lt

    render error, [string "escape.lt"]:20: attempt to index a nil value (global 'lt')
    lua: ttest.lua:17: [string "escape.lt"]:20: attempt to index a nil value (global 'lt')
    stack traceback:
	[C]: in method 'renderFile'
	ttest.lua:17: in main chunk
	[C]: in ?

**Comment by mbalmer** [comment]
Thanks for spotting this.  This must have been introduced when we factored out this code as a standalone module.  I'll look into it.

**Comment by mbalmer** [comment]
This has been fixed.  We forgot to convert the escaping functions when we extracted the template module from a binary that used it. Thanks for the report.
