### ISSUE TITLE
"attempt to close non-closable variable"

### ISSUE THREAD

**Issue by theSundayProgrammer** [arcapos/luatemplate#2]
I have the following html file (template.html) file
       <!DOCTYPE html>
        <html>

        <head>
        <title><%! block title %>Sample Document<%! endblock %></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta content="text/html; charset=iso-8859-2" http-equiv="Content-Type">
        <style>
        .mySlides {display:block;width:100%;}
        .w3-bar{width:100%;overflow:hidden}
        .w3-center .w3-bar{display:inline-block;width:auto}
        .w3-bar-block.w3-center .w3-bar-item{text-align:center}
        .w3-block{display:block;width:100%}
        </style>
        </head>
        
        <body >
        
        <figure class="w3-content w3-section" >
        <img class="mySlides" id="mypix" alt="Mueller Photos">
        <figcaption>Photo by XXX</figcaption>
        </figure>
        <script>
         <%! block vara %><%! endblock %>
        </script>
        <script>
         <%! block varb %><%! endblock %>
        </script>
        
        </body>
        </html>

when I run "lua ttest.lua template.html"  I get

        lua: attempt to close non-closable variable '(C temporary)'
        stack traceback:
	        [C]: in method 'renderFile'
	        ../luatemplate/ttest.lua:17: in main chunk
	        [C]: in ?

However if I remove  " <%! block varb %><%! endblock %>" everything works fine

**Comment by theSundayProgrammer** [comment]
If I put all the <style> in a separate block and include it in a dependency file all is good 
        


        <%! extends template.html %>
        <%! block css %>
        .mySlides {display:block;width:100%;}
        .w3-bar{width:100%;overflow:hidden}
        .w3-center .w3-bar{display:inline-block;width:auto}
        .w3-bar-block.w3-center .w3-bar-item{text-align:center}
        .w3-block{display:block;width:100%}
        .w3-left-align{text-align:left!important}.w3-right-align{text-align:right!important}.w3-justify{text-align:justify!important}.w3-center{text-align:center!important}
        .w3-content,.w3-auto{margin-left:auto;margin-right:auto}.w3-content{max-width:980px}.w3-auto{max-width:1140px}
        .w3-section,.w3-code{margin-top:16px!important;margin-bottom:16px!important}
        <%! endblock %>
        <%! block vara %>
        var image_list="images.json";
        <%! endblock %>
        <%! block varb %>
        var image_lista="imagesA.json";
        <%! endblock %>

**Comment by mbalmer** [comment]
Is this with Lua 5.4?

**Comment by theSundayProgrammer** [comment]
Yes. Lua 5.4.2

**Comment by mbalmer** [comment]
Ok, I will try to find the cause (I am still using 5.3, but of course this has to work with 5.4 as well)

**Comment by mbalmer** [comment]
Cann you attach the exact file that does not work (i.e. not copy paste into an e-mail)?  Extracting template.html from what you posted does not show the error here with 5.4.2 (on RHEL 8, fwiw).

**Comment by theSundayProgrammer** [comment]
Sorry for the inconvenience. I cut and paste the code from above and it all works.

**Comment by theSundayProgrammer** [comment]
Thanks for taking the time to look into it. The message seemed to indicate that a block was not being closed. Hence I tried various options. The situation is a bit bizarre. I spent hours digging through the code and gave up before I raised the issue

**Comment by theSundayProgrammer** [comment]
Turns out I did not update the shared library from the previous version

**Comment by mbalmer** [comment]
So does it work for you as expected now?

**Comment by theSundayProgrammer** [comment]
Linking a file that reproduces 

https://norwestcomputing.com.au/template_issue.html

**Comment by mbalmer** [comment]
Is that already rendered or the source form?

**Comment by mbalmer** [comment]
I need the source of the file, e.g. before it is processed.

**Comment by theSundayProgrammer** [comment]
That is the source. No transformations!

**Comment by mbalmer** [comment]
Ok, I will look at it

**Comment by mbalmer** [comment]
I found the issue and I am now working on a fix.

**Comment by mbalmer** [comment]
luaL_Buffers can not be used intermittently, therefore I added a simple buffer implementation that can be used this way.
